// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity;
using IDCL.Tacama.Core.Entity.Tacama.master;
using Microsoft.EntityFrameworkCore;
#nullable enable

namespace IDCL.Tacama.Core.Contexto.IDCL.Tacama.Core.Contexto
{
    public partial class DbTacamaContext : DbContext
    {
        public DbTacamaContext()
        {
        }

        public DbTacamaContext(DbContextOptions<DbTacamaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<TramaDiario> TramaDiarios { get; set; }
        public virtual DbSet<TramaHistorico> TramaHistoricos { get; set; }
        public virtual DbSet<UsuarioTacama> Usuarios { get; set; }
        public virtual DbSet<UsuarioRol> UsuarioRols { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<ExpPedidoCab> ExpPedidoCabs { get; set; }
        public virtual DbSet<ExpPedidoDet> ExpPedidoDets { get; set; }
        public virtual DbSet<PersonaTacama> Personas { get; set; }
        public virtual DbSet<PersonaDireccion> PersonaDireccions { get; set; }

        public virtual DbSet<ArticuloTacamaCategorium> ArticuloCategoria { get; set; }
        public virtual DbSet<ArticuloTacamaServ> ArticuloServs { get; set; }
        public virtual DbSet<ArticuloServPresentacion> ArticuloServPresentacions { get; set; }


        public virtual DbSet<Condicion> Condicions { get; set; }
        public virtual DbSet<ListaPrecioTacama> ListaPrecios { get; set; }
        public virtual DbSet<ListaPrecioItemTacama> ListaPrecioItems { get; set; }
        public virtual DbSet<VenCanalVentum> VenCanalVenta { get; set; }


        //Master vendedores
        public virtual DbSet<Establecimiento> Establecimientos { get; set; }
        public virtual DbSet<UbigeoSunat> UbigeoSunats { get; set; }
        public virtual DbSet<VenDivision> VenDivisions { get; set; }
        public virtual DbSet<Vendedore> Vendedores { get; set; }
        public virtual DbSet<ZonaTrabajo> ZonaTrabajos { get; set; }

        //Maestros
        public virtual DbSet<AfectacionIgv> AfectacionIgvs { get; set; }
        public virtual DbSet<Almacen> Almacens { get; set; }
        public virtual DbSet<Moneda> Monedas { get; set; }
        public virtual DbSet<ParTabla> ParTablas { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //Maestros

            modelBuilder.ApplyConfiguration(new Configurations.AfectacionIgvConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AlmacenConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MonedaConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ParTablaConfiguration());


            modelBuilder.ApplyConfiguration(new Configurations.RolConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TramaDiarioConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TramaHistoricoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UsuarioConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UsuarioRolConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ClienteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ExpPedidoCabConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ExpPedidoDetConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PersonaConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PersonaDireccionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ArticuloCategoriumConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ArticuloServConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ArticuloServPresentacionConfiguration());


            modelBuilder.ApplyConfiguration(new Configurations.CondicionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ListaPrecioConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ListaPrecioItemConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VenCanalVentumConfiguration());

            //Master vendedores
            modelBuilder.ApplyConfiguration(new Configurations.EstablecimientoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UbigeoSunatConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VenDivisionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VendedoreConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ZonaTrabajoConfiguration());


            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
