// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace IDCL.Tacama.Core.Entity
{
    public partial class ArticuloServPresentacion
    {
        public int IdPresentacion { get; set; }
        public string DesPresentacion { get; set; } = null!;
        public string DesPresentacionInterna { get; set; } = null!;
        public decimal Peso { get; set; }
        public decimal? PesoNeto { get; set; }
        public string? TipodePaleta { get; set; }
        public decimal? CajasPorPaleta { get; set; }
        public decimal? PaletaPorContenedor { get; set; }
        public decimal? CajasPorContenedor { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public List<ExpPedidoDet> ExpPedidoDets { get; set; }
    }
}