// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace IDCL.Tacama.Core.Entity
{
    public partial class ArticuloTacamaCategorium
    {
      

        /// <summary>
        /// id de Empresa
        /// </summary>
        public int IdEmpresa { get; set; }
        /// <summary>
        /// tipo de Articulo de partabla grupo=333000
        /// </summary>
        public int IdTipoArticulo { get; set; }
        /// <summary>
        /// codigo de la categoria
        /// </summary>
        public string CodCategoria { get; set; } = null!;
        /// <summary>
        /// nombre del a categoria
        /// </summary>
        public string NombreCategoria { get; set; } = null!;
        /// <summary>
        /// nivel de la categoria segun lo requiera 1,2,3,,,,,
        /// </summary>
        public int NumNivel { get; set; }
        /// <summary>
        /// indica el nivel final
        /// </summary>
        public string IndUltimoNivel { get; set; } = null!;
        /// <summary>
        /// codigo de la categoria superioro para niveles mayores a 1
        /// </summary>
        public string? CodCategoriaSup { get; set; }
        /// <summary>
        /// indica la cuenta
        /// </summary>
        public bool? IndCuenta { get; set; }
        /// <summary>
        /// version del plan de cuentas.
        /// </summary>
        public string? NumVerPlanCuentas { get; set; }
        /// <summary>
        /// cuentas para gastos administrativos
        /// </summary>
        public string? CodCuentaAdm { get; set; }
        /// <summary>
        /// cuenta para gastos de ventas
        /// </summary>
        public string? CodCuentaVta { get; set; }
        /// <summary>
        /// cuenta para gastos de produccion
        /// </summary>
        public string? CodCuentaPro { get; set; }
        /// <summary>
        /// cuenta de consumo.
        /// </summary>
        public string? CodCuentaConsumo { get; set; }
        /// <summary>
        /// cuenta para valor venta en el caso de ventas.
        /// </summary>
        public string? CodCuentaVenta { get; set; }
        /// <summary>
        /// cuenta para la 12 en casos especiales.
        /// </summary>
        public string? CodCuentaVenta12 { get; set; }
        /// <summary>
        /// cuenta para la provision de compras.
        /// </summary>
        public string? CodCuentaCompra { get; set; }
        /// <summary>
        /// cuenta para la provision de compra Por Recibir
        /// </summary>
        public string? CodCuentaPorRecibir { get; set; }
        /// <summary>
        /// para el caso de ventas relacionadas o vinculadas
        /// </summary>
        public string? CodCuentaVentaRelacionada { get; set; }
        public string? CodCuentaVentaDscto { get; set; }
        /// <summary>
        /// no se usa
        /// </summary>
        public int? IdTipoArticuloAsoc { get; set; }
        /// <summary>
        /// no se usa
        /// </summary>
        public string? CodCategoriaAsoc { get; set; }
        /// <summary>
        /// no se usa
        /// </summary>
        public bool? IndManejaUnmMayor { get; set; }
        /// <summary>
        /// no se usa
        /// </summary>
        public bool IndManejaUnmMenor { get; set; }
        /// <summary>
        /// Auditoria
        /// </summary>
        public string? UsuarioRegistro { get; set; }
        /// <summary>
        /// Auditoria
        /// </summary>
        public DateTime? FechaRegistro { get; set; }
        /// <summary>
        /// Auditoria
        /// </summary>
        public string? UsuarioModificacion { get; set; }
        /// <summary>
        /// Auditoria
        /// </summary>
        public DateTime? FechaModificacion { get; set; }

        public List<ArticuloTacamaServ> ArticuloServs { get; set; }
    }
}