// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace IDCL.Tacama.Core.Entity
{
    public partial class ArticuloTacamaServ
    {
        /// <summary>
        /// id de la Empresa
        /// </summary>
        public int IdEmpresa { get; set; }
        /// <summary>
        /// id Articulo se genera en automatico
        /// </summary>
        public int IdArticulo { get; set; }
        /// <summary>
        /// codigo de Articulo para libre manejo de la empresa codigo interno
        /// </summary>
        public string? CodArticulo { get; set; }
        /// <summary>
        /// Descripcion del Articulo
        /// </summary>
        public string? NomArticulo { get; set; }
        /// <summary>
        /// Descripcion en Ingles del Articulo para cotizaciones
        /// </summary>
        public string? NomArticuloEng { get; set; }
        /// <summary>
        /// nombre largo del Articulo
        /// </summary>
        public string? NomArticuloLargo { get; set; }
        /// <summary>
        /// nombre corto para estadisticos.
        /// </summary>
        public string? NomCorto { get; set; }
        /// <summary>
        /// indica si manejara codigo de barras true =SI, false = NO
        /// </summary>
        public bool? IndCodBarra { get; set; }
        /// <summary>
        /// codigo de Barra 1
        /// </summary>
        public string? CodBarra { get; set; }
        /// <summary>
        /// codigo de Barra 2
        /// </summary>
        public string? CodBarra2 { get; set; }
        /// <summary>
        /// codigo de Barra 3
        /// </summary>
        public string? CodBarra3 { get; set; }
        /// <summary>
        /// codigo de Barra 4
        /// </summary>
        public string? CodBarra4 { get; set; }
        /// <summary>
        /// codigo de Barra 5
        /// </summary>
        public string? CodBarra5 { get; set; }
        /// <summary>
        /// Tipo de Unidad de Medida para Almacen
        /// </summary>
        public int? CodTipoMedAlmacen { get; set; }
        /// <summary>
        /// Codigo de Unidad de Medida para Almacen
        /// </summary>
        public int? CodUniMedAlmacen { get; set; }
        /// <summary>
        /// no se usa para tacama
        /// </summary>
        public int? IdTipoMedEnvase { get; set; }
        /// <summary>
        /// no se usa para tacama
        /// </summary>
        public int? IdUniMedEnvase { get; set; }
        /// <summary>
        /// no se usa para tacama
        /// </summary>
        public int? CodTipoMedPresentacion { get; set; }
        /// <summary>
        /// no se usa para tacama
        /// </summary>
        public int? CodUniMedPresentacion { get; set; }
        /// <summary>
        /// se usaba para saber el contenido de botellas dentro de una caja
        /// </summary>
        public decimal? Contenido { get; set; }
        /// <summary>
        /// capacidad en c.c. por ejemplo 750
        /// </summary>
        public decimal? Capacidad { get; set; }
        /// <summary>
        /// el Peso por Botella.
        /// </summary>
        public decimal? PesoUnitario { get; set; }
        /// <summary>
        /// tipo de articulo se especifica en la tabla partabla grupo=333000
        /// </summary>
        public int? IdTipoArticulo { get; set; }
        /// <summary>
        /// codigo de la categoria
        /// </summary>
        public string? CodCategoria { get; set; }
        /// <summary>
        /// indicar linea de Venta
        /// </summary>
        public bool? IndLineaVenta { get; set; }
        /// <summary>
        /// codigo de la linea de venta
        /// </summary>
        public string? CodLineaVenta { get; set; }
        /// <summary>
        /// no se usa
        /// </summary>
        public int? IdTipoAlmacen { get; set; }
        /// <summary>
        /// Clase de articulo con la tabla ClaseArticulo
        /// </summary>
        public int? IdTipo { get; set; }
        /// <summary>
        /// si el codigo del articulo es automatico se combina de lo contrario no se combina
        /// </summary>
        public bool? Combinar { get; set; }
        /// <summary>
        /// id del Articulo Base del Producto.
        /// </summary>
        public int? IdArticuloBase { get; set; }
        /// <summary>
        /// id de la presentacion por ejemplo no se usa actualmente
        /// </summary>
        public int? IdPresentacion { get; set; }
        /// <summary>
        /// nombre de la imagen real
        /// </summary>
        public string? NombreReal { get; set; }
        /// <summary>
        /// nombre de la imagen guardada
        /// </summary>
        public string? NombreImagen { get; set; }
        /// <summary>
        /// extension del archivo que contiene la imagen
        /// </summary>
        public string? Extension { get; set; }
        /// <summary>
        /// codigo del color del articulo
        /// </summary>
        public int? CodColor { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public int? CodMaterial { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public int? CodCapellada { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public int? CodTaco { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public int? CodEstilo { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public int? CodForro { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public int? CodPlanta { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public int? CodEstacion { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public string? Horma { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public decimal? MedAncho { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public decimal? MedLargo { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public decimal? AltPlataforma { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public decimal? Compartimiento { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public decimal? BolInterno { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public decimal? BolExterno { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public bool? IndCuero { get; set; }
        /// <summary>
        /// solo para calzados
        /// </summary>
        public int? CodSerie { get; set; }
        /// <summary>
        /// codigo de la marca
        /// </summary>
        public int? CodModelo { get; set; }
        /// <summary>
        /// codigo del modelo
        /// </summary>
        public int? CodMarca { get; set; }
        /// <summary>
        /// no se usa
        /// </summary>
        public string? Sku { get; set; }
        /// <summary>
        /// indica si esta afecto a detraccion
        /// </summary>
        public bool? IndDetraccion { get; set; }
        /// <summary>
        /// tipo de detraccion afecto.
        /// </summary>
        public string? TipDetraccion { get; set; }
        /// <summary>
        /// si esta activo o de baja.
        /// </summary>
        public bool FlagActivo { get; set; }
        /// <summary>
        /// fecha de cese del articulo
        /// </summary>
        public DateTime? FecCese { get; set; }
        /// <summary>
        /// no se usa
        /// </summary>
        public string? CodigoSunat { get; set; }
        /// <summary>
        /// no se usa
        /// </summary>
        public bool? IndCodSunat { get; set; }
        /// <summary>
        /// tipo de afectacion del articulo
        /// </summary>
        public int? TipoAfectacion { get; set; }
        /// <summary>
        /// si esta afecto a igv
        /// </summary>
        public bool? IndAfectoIgv { get; set; }
        /// <summary>
        /// si esta afecto a isc
        /// </summary>
        public bool? IndAfectoIsc { get; set; }
        /// <summary>
        /// indicar concepto de servicio o gasto
        /// </summary>
        public bool IndConcepto { get; set; }
        /// <summary>
        /// codigo del concepto asociado a los log_conceptosvarios
        /// </summary>
        public int? IdConcepto { get; set; }
        /// <summary>
        /// no se usa
        /// </summary>
        public bool? IndCodEquivalente { get; set; }
        /// <summary>
        /// no se usa
        /// </summary>
        public string? CodEquivalente { get; set; }
        /// <summary>
        /// indica medida del papel o carton
        /// </summary>
        public bool? IndMedida { get; set; }
        /// <summary>
        /// dimension del corte del papel o carton
        /// </summary>
        public decimal? Ancho { get; set; }
        /// <summary>
        /// dimension del corte del papel o carton
        /// </summary>
        public decimal? Largo { get; set; }
        /// <summary>
        /// calibre para el caso de carton
        /// </summary>
        public decimal? Calibre { get; set; }
        /// <summary>
        /// solo para el caso de papel
        /// </summary>
        public decimal? Gramaje { get; set; }
        /// <summary>
        /// color del articulo
        /// </summary>
        public string? DesColor { get; set; }
        /// <summary>
        /// idFormato de Registro generalmente debe ser 0
        /// </summary>
        public int IdFormato { get; set; }
        /// <summary>
        /// Para compras con Demasias en Logisticas como las etiquetas
        /// </summary>
        public bool? IndCompraDemasia { get; set; }
        /// <summary>
        /// Porcentajes para las compras con Demasia
        /// </summary>
        public decimal? PorcentajeDemasia { get; set; }
        /// <summary>
        /// id Partida Presupuestal
        /// </summary>
        public int? IdPartidaPresupuestal { get; set; }
        /// <summary>
        /// no se usa en tacama
        /// </summary>
        public decimal? DensidadDesde { get; set; }
        /// <summary>
        /// no se usa en tacama
        /// </summary>
        public decimal? DensidadHasta { get; set; }
        /// <summary>
        /// no se usa en tacama
        /// </summary>
        public decimal? PhDesde { get; set; }
        /// <summary>
        /// no se usa en tacama
        /// </summary>
        public decimal? PhHasta { get; set; }
        public int? FactorEmpaque { get; set; }
        /// <summary>
        /// Auditoria
        /// </summary>
        public string? UsuarioRegistro { get; set; }
        /// <summary>
        /// Auditoria
        /// </summary>
        public DateTime? FechaRegistro { get; set; }
        /// <summary>
        /// Auditoria
        /// </summary>
        public string? UsuarioModificacion { get; set; }
        /// <summary>
        /// Auditoria
        /// </summary>
        public DateTime? FechaModificacion { get; set; }

        public ArticuloTacamaCategorium? ArticuloCategorium { get; set; }
        public List<ExpPedidoDet> ExpPedidoDets { get; set; }
    }
}