// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using IDCL.Tacama.Core.Entity.Tacama.Customer;

namespace IDCL.Tacama.Core.Entity
{
    public partial class Cliente
    {
        public int IdPersona { get; set; }
        public int IdEmpresa { get; set; }
        public string? SiglaComercial { get; set; }
        public int? TipoCliente { get; set; }
        public DateTime? FecInscripcion { get; set; }
        public DateTime? FecInicioEmpresa { get; set; }
        public int? TipConstitucion { get; set; }
        public int? TipRegimen { get; set; }
        public int? CatCliente { get; set; }
        public bool? IndEstado { get; set; }
        public DateTime? FecBaja { get; set; }
        public bool? IndVinculada { get; set; }
        public int? Zona { get; set; }
        public string? IdCcostos { get; set; }
        public int Calificacion { get; set; }
        public string UsuarioRegistro { get; set; } = null!;
        public DateTime FechaRegistro { get; set; }
        public string UsuarioModificacion { get; set; } = null!;
        public DateTime FechaModificacion { get; set; }

        public PersonaTacama IdPersonaNavigation { get; set; } = null!;

        public List<ClienteAgenciaEnvio> ClienteAgenciaEnvios { get; set; }
        public List<ClienteAseguradora> ClienteAseguradoras { get; set; }
        public List<ClienteAsociado> ClienteAsociados { get; set; }
        public List<ClienteAval> ClienteAvals { get; set; }
        public List<ClienteContacto> ClienteContactos { get; set; }
        public List<ClienteRepLegal> ClienteRepLegals { get; set; }

    }
}