// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace IDCL.Tacama.Core.Entity
{
    public partial class Condicion
    {
        public int IdTipCondicion { get; set; }
        public int IdCondicion { get; set; }
        public string? DesCondicion { get; set; }
        public string? DesCondicionIngles { get; set; }
        public int? IdClasificacion { get; set; }
        public string? DesDias { get; set; }
        public bool? GeneraLetra { get; set; }
        public bool? Credito { get; set; }
        public bool? SeCobra { get; set; }
        public bool? ManejaUnidad { get; set; }
        public bool? TGratuita { get; set; }
        public bool? ConImpuesto { get; set; }
        public bool? NcDescuentos { get; set; }
        public bool? TFilial { get; set; }
        public bool? IndCreditoCobranza { get; set; }
        public bool? IndDias { get; set; }
        public bool? TPromocion { get; set; }
        public int? IdListaPrecio { get; set; }
        public bool? FlagListaActivo { get; set; }
        public bool? IndIngreso { get; set; }
        public string? CodSunatIngreso { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
    }
}