// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace IDCL.Tacama.Core.Entity.Tacama.master
{
    public partial class Almacen
    {
        /// <summary>
        /// id de la empresa
        /// </summary>
        public int IdEmpresa { get; set; }
        /// <summary>
        /// id del almacen es un correlativo
        /// </summary>
        public int IdAlmacen { get; set; }
        /// <summary>
        /// clase de almacen
        /// </summary>
        public int? Clase { get; set; }
        /// <summary>
        /// tipo de almacen de acuerdo a partabla grupo =333000
        /// </summary>
        public int? TipAlmacen { get; set; }
        /// <summary>
        /// descripcion de almacen
        /// </summary>
        public string? DesAlmacen { get; set; }
        /// <summary>
        /// nombre corto del almacen
        /// </summary>
        public string? DesCorta { get; set; }
        /// <summary>
        /// direccion del almacen
        /// </summary>
        public string? Direccion { get; set; }
        /// <summary>
        /// valida el stock del almacen
        /// </summary>
        public bool? VerificaStock { get; set; }
        /// <summary>
        /// valida el Lote del almacen
        /// </summary>
        public bool? VerificaLote { get; set; }
        /// <summary>
        /// Tipo de Numeracion normalmente usar consecutivo.
        /// </summary>
        public string? TipoNumeracion { get; set; }
        /// <summary>
        /// nombre del responsable del almacen
        /// </summary>
        public string? DesResponsable { get; set; }
        /// <summary>
        /// correo del responsable del almacen
        /// </summary>
        public string? EmailResponsable { get; set; }
        /// <summary>
        /// telefono del responsable del almacen
        /// </summary>
        public string? TlfResponsable { get; set; }
        /// <summary>
        /// centro de costos por default.
        /// </summary>
        public string? IdCcostos { get; set; }
        /// <summary>
        /// estado del almacen 1 activo , 0 de baja
        /// </summary>
        public bool? IndEstado { get; set; }
        /// <summary>
        /// fecha de baja cuando es 0
        /// </summary>
        public DateTime? FecBaja { get; set; }
        /// <summary>
        /// 1 si el almacen va manejar ubicaciones
        /// </summary>
        public bool? IndUbicacion { get; set; }
        /// <summary>
        /// indicar ubicacion generica
        /// </summary>
        public string? IndUbiGenerica { get; set; }
        /// <summary>
        /// id de Ubicacion
        /// </summary>
        public string? IdUbicacion { get; set; }
        /// <summary>
        /// Siglas del Almacen
        /// </summary>
        public string? SiglaLoteAlmacen { get; set; }
        /// <summary>
        /// codigo del establecimiento segun sunat
        /// </summary>
        public string? CodEstablecimiento { get; set; }
        /// <summary>
        /// indica almacen por default.
        /// </summary>
        public bool? IndDefault { get; set; }
        /// <summary>
        /// codigo de ubigeo del almacen
        /// </summary>
        public string? CodUbigeoAlm { get; set; }
        /// <summary>
        /// id de empresa que va administrarlo externamente
        /// </summary>
        public int? IdEmpresaAdmin { get; set; }
        public bool? NoUsar { get; set; }
        /// <summary>
        /// Auditoria
        /// </summary>
        public string? UsuarioRegistro { get; set; }
        /// <summary>
        /// Auditoria
        /// </summary>
        public DateTime? FechaRegistro { get; set; }
        /// <summary>
        /// Auditoria
        /// </summary>
        public string? UsuarioModificacion { get; set; }
        /// <summary>
        /// Auditoria
        /// </summary>
        public DateTime? FechaModificacion { get; set; }
    }
}