// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace IDCL.Tacama.Core.Entity.Tacama.master
{
    public partial class Moneda
    {
        public string IdMoneda { get; set; } = null!;
        public string? DesMoneda { get; set; }
        public string? DesAbreviatura { get; set; }
        public string? Iso4217 { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModifica { get; set; }
    }
}