// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace IDCL.Tacama.Core.Entity.Tacama.master
{
    public partial class VenDivision
    {
        public int IdEmpresa { get; set; }
        public int IdDivision { get; set; }
        public string? DesDivision { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
    }
}