// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace IDCL.Tacama.Core.Entity.Tacama.master
{
    public partial class ZonaTrabajo
    {
        public int IdEmpresa { get; set; }
        public int IdLocal { get; set; }
        public int IdEstablecimiento { get; set; }
        public int IdZona { get; set; }
        public string? Descripcion { get; set; }
        public bool? Principal { get; set; }
        public string? IdCcostos { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
    }
}