// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace IDCL.Tacama.Core.Entity.Tacama.Customer
{
    public partial class ClienteAsociado
    {
        public int IdPersona { get; set; }
        public int IdEmpresa { get; set; }
        public int IdAsociado { get; set; }
        public string? RazonSocial { get; set; }
        public string? Ruc { get; set; }
        public string? Direccion { get; set; }
        public string UsuarioRegistro { get; set; } = null!;
        public DateTime FechaRegistro { get; set; }
        public string UsuarioModificacion { get; set; } = null!;
        public DateTime FechaModificacion { get; set; }

        public Cliente Id { get; set; } = null!;
    }
}