// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace IDCL.Tacama.Core.Entity.Tacama.Customer
{
    public partial class ClienteAval
    {
        public int IdEmpresa { get; set; }
        public int IdPersona { get; set; }
        public int IdAval { get; set; }
        public int? TipoDocumento { get; set; }
        public string? NroDocumento { get; set; }
        public string? RazonSocial { get; set; }
        public string? Direccion { get; set; }
        public string? Telefonos { get; set; }
        public string? Email { get; set; }
        public bool? EsPrincipal { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public Cliente Id { get; set; } = null!;
    }
}