// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace IDCL.Tacama.Core.Entity.Tacama.Customer
{
    public partial class ClienteAgenciaEnvio
    {
        public int IdPersona { get; set; }
        public int IdEmpresa { get; set; }
        public int IdAgenciaEnvio { get; set; }
        public int? IdDireccion { get; set; }
        public bool? Predeterminado { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public Cliente Id { get; set; } = null!;
    }
}