// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace IDCL.Tacama.Core.Entity.Tacama.Customer
{
    public partial class ClienteContacto
    {
        public int IdPersona { get; set; }
        public int IdEmpresa { get; set; }
        public int IdItem { get; set; }
        public int? IdSistema { get; set; }
        public string? NroDocumento { get; set; }
        public string? ApePaterno { get; set; }
        public string? ApeMaterno { get; set; }
        public string? Nombres { get; set; }
        public string? Ubicacion { get; set; }
        public string? Telefono1 { get; set; }
        public string? Telefono2 { get; set; }
        public string? Celular1 { get; set; }
        public string? Celular2 { get; set; }
        public string? Correo1 { get; set; }
        public string? Correo2 { get; set; }
        public string? UsuarioRegistro { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string? UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }

        public Cliente Id { get; set; } = null!;
    }
}