// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
namespace IDCL.Tacama.Core.Entity.Tacama.Customer
{
    public partial class ClienteRepLegal
    {
        public int IdPersona { get; set; }
        public int IdEmpresa { get; set; }
        public int IdItem { get; set; }
        public string? NroDoc { get; set; }
        public string? Nombres { get; set; }
        public string? ApePaterno { get; set; }
        public string? ApeMaterno { get; set; }
        public string? NombreReal { get; set; }
        public string? NombreImagen { get; set; }
        public string? Extension { get; set; }
        public string UsuarioRegistro { get; set; } = null!;
        public DateTime FechaRegistro { get; set; }
        public string UsuarioModificacion { get; set; } = null!;
        public DateTime FechaModificacion { get; set; }

        public Cliente Id { get; set; } = null!;
    }
}