using IDCL.AVGUST.SIP.Entity.Tacama.SpEntity;

public class GetSpPedidoCabNacional
{
    public int IdEmpresa { get; set; }
    public int IdLocal { get; set; }
    public int IdPedido { get; set; }
    public string CodPedidoCad { get; set; }
    public DateTime Fecha { get; set; }
    public DateTime? FechaEntrega { get; set; }
    public int IdConsignatario { get; set; }
    public int IdNotificar { get; set; }
    public string? RucNotificador { get; set; }
    public string? DesNotificador { get; set; }
    public string? DirNotificador { get; set; }
    public int IdFacturar { get; set; }
    public string RucCliente { get; set; }
    public string DesFacturar { get; set; }
    public string DireccionCompleta { get; set; }
    public string IdMoneda { get; set; }
    public string DesMoneda { get; set; }
    public string Observacion { get; set; }
    public string Indicaciones { get; set; }
    public string? NroGuia { get; set; }
    public DateTime? FecFactura { get; set; }
    public string? NroFactura { get; set; }
    public string TipoGeneracion { get; set; }
    public int IdVendedor { get; set; }
    public string Vendedor { get; set; }
    public string NumDocVendedor { get; set; }
    public string TelVendedor { get; set; }
    public string EmailVendedor { get; set; }
    public string Cargo { get; set; }
    public string NombreCotizacion { get; set; }
    public int IdEstablecimiento { get; set; }
    public int IdZona { get; set; }
    public string Tipo { get; set; }
    public string Estado { get; set; }
    public int IdFormaPago { get; set; }
    public int IdTipCondicion { get; set; }
    public int IdCondicion { get; set; }
    public string DesCondicion { get; set; }
    public decimal TotSubTotal { get; set; }
    public decimal TotDscto1 { get; set; }
    public decimal TotDscto2 { get; set; }
    public decimal TotDscto3 { get; set; }
    public decimal TotIsc { get; set; }
    public decimal TotIgv { get; set; }
    public decimal TotTotal { get; set; }
    public int IdSucursalCliente { get; set; }
    public string PuntoPartida { get; set; }
    public string PuntoLlegada { get; set; }
    public int IdTransporte { get; set; }
    public string? RazonSocialTransporte { get; set; }
    public string? RucTransporte { get; set; }
    public int TipoDoc { get; set; }
    public string NemoTipoDoc { get; set; }
    public string IndCotPed { get; set; }
    public int IdPedidoEnlace { get; set; }
    public int IdDivision { get; set; }
    public int IdCanalVenta { get; set; }
    public string NombreCanal { get; set; }
    public int IdAlmacen { get; set; }
    public string IndBloqueaLista { get; set; }
    public string IndBloqueaAlmacen { get; set; }
    public string IndTipoPedido { get; set; }
    public decimal PorDscto { get; set; }
    public string FlagListaActivo { get; set; }
    public int IdListaPrecio { get; set; }
    public string DesListaPrecio { get; set; }
    public string IndDsctoProntoPago { get; set; }
    public decimal DsctoProntoPago { get; set; }
    public string IndBonificacion { get; set; }
    public string IndObsStock { get; set; }
    public string ObsStock { get; set; }
    public string IndObsCredito { get; set; }
    public string ObsCredito { get; set; }
    public int Aprobacion { get; set; }
    public string MensajeAprobacion { get; set; }
    public int AprobacionPrecios { get; set; }
    public string MensajeAprobacionPrecios { get; set; }
    public string IdMonedaLineaCredito { get; set; }
    public decimal TipCambio { get; set; }
    public decimal LineaCredito { get; set; }
    public decimal CreditoLetras { get; set; }
    public decimal CreditoFacturas { get; set; }
    public decimal CreditoDocumento { get; set; }
    public decimal LineaDisponible { get; set; }
    public int IdTipoCompra { get; set; }
    public int AlmacenIngreso { get; set; }
    public string OrdenDeCompraNum { get; set; }
    public decimal LetraNoAceptadas { get; set; }
    public decimal LetraProtestadas { get; set; }
    public int IdiomaImpresion { get; set; }
    public int IdContacto { get; set; }
    public int IdPaisOrigen { get; set; }
    public int IdPaisDestino { get; set; }
    public int IdIncotermsPrecio { get; set; }
    public int IdIncoterms { get; set; }
    public string? DesNombreContacto { get; set; }
    public string? PaisOrigen { get; set; }
    public string? PaisDestino { get; set; }
    public string? PaisOrigenEng { get; set; }
    public string? PaisDestinoEng { get; set; }
    public string? DesIncotermsPrecio { get; set; }
    public string? DesIncoterms { get; set; }
    public string PuertoOrigen { get; set; }
    public string PuertoDestino { get; set; }
    public int DiasValidez { get; set; }
    public string Contacto { get; set; }
    public string Telefono { get; set; }
    public string UbigeoCot { get; set; }
    public string UsuarioRegistro { get; set; }
    public DateTime FechaRegistro { get; set; }
    public string UsuarioModificacion { get; set; }
    public DateTime FechaModificacion { get; set; }
    public List<GetSpPedidoNacionalDet> detalle { get; set; }
    public List<GetSpListarCuentasParaDoc> cuentas { get; set; }
}
