public class GetSpPedidoNacionalDet
{
    public int IdEmpresa { get; set; }
    public int IdPedido { get; set; }
    public int IdLocal { get; set; }
    public int IdItem { get; set; }
    public string IndArticuloNuevo { get; set; }
    public int IdTipoPrecio { get; set; }
    public int IdArticulo { get; set; }
    public string NomArticulo { get; set; }
    public string CodArticulo { get; set; }
    public string DesArticulo { get; set; }
    public string DesArticuloCompuesto { get; set; }
    public string IndSinStock { get; set; }
    public decimal Cantidad { get; set; }
    public decimal CantidadUnit { get; set; }
    public decimal CantidadFinal { get; set; }
    public decimal PrecioUnitario { get; set; }
    public decimal PrecioConImpuesto { get; set; }
    public decimal Dscto1 { get; set; }
    public decimal Dscto2 { get; set; }
    public decimal Dscto3 { get; set; }
    public decimal PorDscto1 { get; set; }
    public decimal PorDscto2 { get; set; }
    public decimal PorDscto3 { get; set; }
    public string FlgIgv { get; set; }
    public decimal Isc { get; set; }
    public decimal Igv { get; set; }
    public decimal SubTotal { get; set; }
    public decimal Total { get; set; }
    public decimal PorIsc { get; set; }
    public decimal PorIgv { get; set; }
    public int IdTipoMedida { get; set; }
    public int IdUMedida { get; set; }
    public string CodLineaVenta { get; set; }
    public string DesUnidadMed { get; set; }
    public string DesUniPrese { get; set; }
    public string IndManejaUnmMayor { get; set; }
    public string IndManejaUnmMenor { get; set; }
    public string NomUMedidaEnv { get; set; }
    public string NomUMedidaPres { get; set; }
    public decimal Capacidad { get; set; }
    public decimal Contenido { get; set; }
    public decimal PesoUnitario { get; set; }
    public int IdTipoArticulo { get; set; }
    public int IdAlmacen { get; set; }
    public decimal Stock { get; set; }
    public string Lote { get; set; }
    public decimal StockDisponible { get; set; }
    public string SiglaEmpresa { get; set; }
    public string DesAlmOrigen { get; set; }
    public string LoteAlmacen { get; set; }
    public string LoteProveedor { get; set; }
    public string NroOt { get; set; }
    public string IndCalculo { get; set; }
    public string TipoImpSelectivo { get; set; }
    public string IndDetraccion { get; set; }
    public string TipDetraccion { get; set; }
    public decimal TasaDetraccion { get; set; }
    public string FlgAfectacionIgv { get; set; }
    public string TipoAfectacionIgv { get; set; }
    public string TipArticulo { get; set; }
    public string UsuarioRegistro { get; set; }
    public DateTime FechaRegistro { get; set; }
    public string UsuarioModificacion { get; set; }
    public DateTime FechaModificacion { get; set; }
    public string IndPrecioUnit { get; set; }
    public decimal PrecioUnitIni { get; set; }
    public string IndDistribuirLote { get; set; }
    public string IndNoAtender { get; set; }
    public string ObsNoAtender { get; set; }
    public decimal CantidadNoAtendida { get; set; }
    public decimal CantidadAtender { get; set; }
    public int ItemPrecio { get; set; }
    public string VerImagen { get; set; }
    public string ChkPromo { get; set; }
    public string? IndPrecioPromocional { get; set; }
    public decimal? PrecioUnitPromocional { get; set; }
    public string ArtEng { get; set; }
    public string? IndUMedida { get; set; }
    public decimal? ContenidoUMedida { get; set; }
    public decimal? CantidadUMedida { get; set; }
    public string IndPack { get; set; }
    public int? IdArticuloPack { get; set; }
    public string? CodArticuloPack { get; set; }
    public string? NomArticuloPack { get; set; }
    public decimal? CantidadPack { get; set; }
    public GetSpArticuloServForPdf itemArticulo { get; set; }
}
