// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class ArticuloServPresentacionConfiguration : IEntityTypeConfiguration<ArticuloServPresentacion>
    {
        public void Configure(EntityTypeBuilder<ArticuloServPresentacion> entity)
        {
            entity.HasKey(e => e.IdPresentacion)
                .HasName("PK_exp_Presentacion");

            entity.ToTable("ArticuloServPresentacion");

            entity.Property(e => e.IdPresentacion).HasColumnName("idPresentacion");

            entity.Property(e => e.CajasPorContenedor).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.CajasPorPaleta).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.DesPresentacion)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("desPresentacion");

            entity.Property(e => e.DesPresentacionInterna)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("desPresentacionInterna");

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.PaletaPorContenedor).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.Peso).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.PesoNeto).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.TipodePaleta)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ArticuloServPresentacion> entity);
    }
}
