// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity.Tacama.Customer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class ClienteAseguradoraConfiguration : IEntityTypeConfiguration<ClienteAseguradora>
    {
        public void Configure(EntityTypeBuilder<ClienteAseguradora> entity)
        {
            entity.HasKey(e => new { e.IdPersona, e.IdEmpresa, e.IdItem });

            entity.ToTable("ClienteAseguradora");

            entity.Property(e => e.IdPersona).HasColumnName("idPersona");

            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");

            entity.Property(e => e.IdItem)
                .ValueGeneratedOnAdd()
                .HasColumnName("idItem");

            entity.Property(e => e.Desde).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.Hasta).HasColumnType("smalldatetime");

            entity.Property(e => e.IdAseguradora).HasColumnName("idAseguradora");

            entity.Property(e => e.IdMoneda)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("idMoneda");

            entity.Property(e => e.Monto).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Id)
                .WithMany(p => p.ClienteAseguradoras)
                .HasForeignKey(d => new { d.IdPersona, d.IdEmpresa })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ClienteAseguradora_Cliente");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClienteAseguradora> entity);
    }
}
