// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity.Tacama.Customer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class ClienteAsociadoConfiguration : IEntityTypeConfiguration<ClienteAsociado>
    {
        public void Configure(EntityTypeBuilder<ClienteAsociado> entity)
        {
            entity.HasKey(e => new { e.IdPersona, e.IdEmpresa, e.IdAsociado });

            entity.Property(e => e.IdPersona).HasColumnName("idPersona");

            entity.Property(e => e.IdAsociado).ValueGeneratedOnAdd();

            entity.Property(e => e.Direccion).HasMaxLength(200);

            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("datetime");

            entity.Property(e => e.RazonSocial).HasMaxLength(50);

            entity.Property(e => e.Ruc)
                .HasMaxLength(25)
                .HasColumnName("RUC");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Id)
                .WithMany(p => p.ClienteAsociados)
                .HasForeignKey(d => new { d.IdPersona, d.IdEmpresa })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ClienteAsociados_Cliente");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClienteAsociado> entity);
    }
}
