// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity.Tacama.Customer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class ClienteAgenciaEnvioConfiguration : IEntityTypeConfiguration<ClienteAgenciaEnvio>
    {
        public void Configure(EntityTypeBuilder<ClienteAgenciaEnvio> entity)
        {
            entity.HasKey(e => new { e.IdPersona, e.IdEmpresa, e.IdAgenciaEnvio });

            entity.ToTable("ClienteAgenciaEnvio");

            entity.Property(e => e.IdPersona).HasColumnName("idPersona");

            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");

            entity.Property(e => e.IdAgenciaEnvio).HasColumnName("idAgenciaEnvio");

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.IdDireccion).HasColumnName("idDireccion");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Id)
                .WithMany(p => p.ClienteAgenciaEnvios)
                .HasForeignKey(d => new { d.IdPersona, d.IdEmpresa })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ClienteAgenciaEnvio_Cliente");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClienteAgenciaEnvio> entity);
    }
}
