// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity.Tacama.Customer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class ClienteContactoConfiguration : IEntityTypeConfiguration<ClienteContacto>
    {
        public void Configure(EntityTypeBuilder<ClienteContacto> entity)
        {
            entity.HasKey(e => new { e.IdPersona, e.IdEmpresa, e.IdItem });

            entity.ToTable("ClienteContacto");

            entity.Property(e => e.IdPersona).HasColumnName("idPersona");

            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");

            entity.Property(e => e.IdItem)
                .ValueGeneratedOnAdd()
                .HasColumnName("idItem");

            entity.Property(e => e.ApeMaterno).HasMaxLength(50);

            entity.Property(e => e.ApePaterno).HasMaxLength(50);

            entity.Property(e => e.Celular1)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.Celular2)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.Correo1).HasMaxLength(100);

            entity.Property(e => e.Correo2).HasMaxLength(100);

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.IdSistema).HasColumnName("idSistema");

            entity.Property(e => e.Nombres).HasMaxLength(50);

            entity.Property(e => e.NroDocumento).HasMaxLength(25);

            entity.Property(e => e.Telefono1)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Telefono2)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Ubicacion)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Id)
                .WithMany(p => p.ClienteContactos)
                .HasForeignKey(d => new { d.IdPersona, d.IdEmpresa })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ClienteContacto_Cliente");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClienteContacto> entity);
    }
}
