// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class CondicionConfiguration : IEntityTypeConfiguration<Condicion>
    {
        public void Configure(EntityTypeBuilder<Condicion> entity)
        {
            entity.HasKey(e => new { e.IdTipCondicion, e.IdCondicion })
                .HasName("PK__Condicio__725D74C1039D766A");

            entity.ToTable("Condicion");

            entity.Property(e => e.IdTipCondicion).HasColumnName("idTipCondicion");

            entity.Property(e => e.IdCondicion).HasColumnName("idCondicion");

            entity.Property(e => e.CodSunatIngreso)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("codSunatIngreso");

            entity.Property(e => e.DesCondicion)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("desCondicion");

            entity.Property(e => e.DesCondicionIngles)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("desCondicionIngles");

            entity.Property(e => e.DesDias)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("desDias");

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.IdClasificacion).HasColumnName("idClasificacion");

            entity.Property(e => e.IdListaPrecio).HasColumnName("idListaPrecio");

            entity.Property(e => e.IndCreditoCobranza).HasColumnName("indCreditoCobranza");

            entity.Property(e => e.IndDias).HasColumnName("indDias");

            entity.Property(e => e.IndIngreso).HasColumnName("indIngreso");

            entity.Property(e => e.NcDescuentos).HasColumnName("ncDescuentos");

            entity.Property(e => e.TFilial).HasColumnName("tFilial");

            entity.Property(e => e.TGratuita).HasColumnName("tGratuita");

            entity.Property(e => e.TPromocion).HasColumnName("tPromocion");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Condicion> entity);
    }
}
