// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity.Tacama.master;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class MonedaConfiguration : IEntityTypeConfiguration<Moneda>
    {
        public void Configure(EntityTypeBuilder<Moneda> entity)
        {
            entity.HasKey(e => e.IdMoneda)
                .HasName("PK__Monedas__E14012F470AD0307");

            entity.Property(e => e.IdMoneda)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("idMoneda");

            entity.Property(e => e.DesAbreviatura)
                .HasMaxLength(6)
                .IsUnicode(false)
                .HasColumnName("desAbreviatura");

            entity.Property(e => e.DesMoneda)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("desMoneda");

            entity.Property(e => e.FechaModifica).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.Iso4217)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("ISO_4217");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Moneda> entity);
    }
}
