// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity.Tacama.master;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class ParTablaConfiguration : IEntityTypeConfiguration<ParTabla>
    {
        public void Configure(EntityTypeBuilder<ParTabla> entity)
        {
            entity.HasKey(e => e.IdParTabla)
                .HasName("XPKParTabla");

            entity.ToTable("ParTabla");

            entity.HasIndex(e => e.IdParTabla, "IX_Nemotecnico")
                .IsUnique();

            entity.HasIndex(e => new { e.Grupo, e.IdParTabla, e.Estado }, "IX_ParTablaGrupo");

            entity.HasIndex(e => new { e.Grupo, e.IdParTabla, e.Nombre, e.Estado }, "IX_ParTablaGrupoNombre");

            entity.HasIndex(e => e.Nemotecnico, "IX_ParTablaNemo");

            entity.Property(e => e.IdParTabla).ValueGeneratedNever();

            entity.Property(e => e.Descripcion).HasMaxLength(250);

            entity.Property(e => e.EquivalenciaSunat).HasMaxLength(25);

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.Nemotecnico).HasMaxLength(50);

            entity.Property(e => e.Nombre).HasMaxLength(100);

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.ValorCadena).HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ParTabla> entity);
    }
}
