// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class PersonaConfiguration : IEntityTypeConfiguration<PersonaTacama>
    {
        public void Configure(EntityTypeBuilder<PersonaTacama> entity)
        {
            entity.HasKey(e => e.IdPersona);

            entity.ToTable("Persona");

            entity.HasIndex(e => e.Ruc, "IX_Persona")
                .IsUnique();

            entity.Property(e => e.ApeMaterno)
                .HasMaxLength(50)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.ApePaterno).HasMaxLength(50);

            entity.Property(e => e.Correo).HasMaxLength(100);

            entity.Property(e => e.DireccionCompleta)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.Estado).HasDefaultValueSql("((0))");

            entity.Property(e => e.Fax)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.IdCanalVenta).HasColumnName("idCanalVenta");

            entity.Property(e => e.IdPais).HasColumnName("idPais");

            entity.Property(e => e.IdUbigeo)
                .HasMaxLength(6)
                .IsUnicode(false)
                .HasColumnName("idUbigeo")
                .HasDefaultValueSql("('')");

            entity.Property(e => e.Nombres).HasMaxLength(50);

            entity.Property(e => e.NroDocumento).HasMaxLength(25);

            entity.Property(e => e.RazonSocial).HasMaxLength(200);

            entity.Property(e => e.Ruc)
                .HasMaxLength(25)
                .HasColumnName("RUC");

            entity.Property(e => e.Telefonos)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("telefonos");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Web).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonaTacama> entity);
    }
}
