// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class PersonaDireccionConfiguration : IEntityTypeConfiguration<PersonaDireccion>
    {
        public void Configure(EntityTypeBuilder<PersonaDireccion> entity)
        {
            entity.HasKey(e => new { e.IdPersona, e.IdDireccion })
                .HasName("XPKPersonaDireccion");

            entity.ToTable("PersonaDireccion");

            entity.Property(e => e.IdDireccion).ValueGeneratedOnAdd();

            entity.Property(e => e.Cargo)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.CodUbigeo).HasMaxLength(10);

            entity.Property(e => e.Contacto)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.Correo).HasMaxLength(200);

            entity.Property(e => e.DescripcionSucursal)
                .HasMaxLength(100)
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.DireccionCompleta).HasMaxLength(250);

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.HorarioEntrega)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.IdAgenciaTransportista).HasDefaultValueSql("((0))");

            entity.Property(e => e.Interior).HasMaxLength(5);

            entity.Property(e => e.Lote).HasMaxLength(10);

            entity.Property(e => e.Manzana).HasMaxLength(10);

            entity.Property(e => e.NombreVia).HasMaxLength(100);

            entity.Property(e => e.NombreZona).HasMaxLength(100);

            entity.Property(e => e.NroVia).HasMaxLength(25);

            entity.Property(e => e.Referencia).HasMaxLength(250);

            entity.Property(e => e.Telefono).HasMaxLength(100);

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.IdPersonaNavigation)
                .WithMany(p => p.PersonaDireccions)
                .HasForeignKey(d => d.IdPersona)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonaDireccion_Persona");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PersonaDireccion> entity);
    }
}
