// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity.Tacama.master;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class UbigeoSunatConfiguration : IEntityTypeConfiguration<UbigeoSunat>
    {
        public void Configure(EntityTypeBuilder<UbigeoSunat> entity)
        {
            entity.HasKey(e => e.IdUbigeo)
                .HasName("XPKUbigeo");

            entity.ToTable("UbigeoSunat");

            entity.Property(e => e.IdUbigeo)
                .HasMaxLength(6)
                .IsUnicode(false)
                .HasColumnName("idUbigeo");

            entity.Property(e => e.CodPostal)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codPostal");

            entity.Property(e => e.Departamento)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.Distrito)
                .HasMaxLength(40)
                .IsUnicode(false);

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.IdPais).HasColumnName("idPais");

            entity.Property(e => e.IndBaja)
                .HasColumnName("indBaja")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.Provincia)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UbigeoSunat> entity);
    }
}
