// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class VenCanalVentumConfiguration : IEntityTypeConfiguration<VenCanalVentum>
    {
        public void Configure(EntityTypeBuilder<VenCanalVentum> entity)
        {
            entity.HasKey(e => new { e.IdEmpresa, e.IdCanalVenta });
            entity.ToTable("ven_CanalVenta");
            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");
            entity.Property(e => e.IdCanalVenta).HasColumnName("idCanalVenta");
            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");
            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");
            entity.Property(e => e.IdAlmacen).HasColumnName("idAlmacen");
            entity.Property(e => e.IdListaPrecio).HasColumnName("idListaPrecio");
            entity.Property(e => e.IndBloqueaAlmacen).HasColumnName("indBloqueaAlmacen");
            entity.Property(e => e.IndBloqueaLista).HasColumnName("indBloqueaLista");
            entity.Property(e => e.IndEstado).HasColumnName("indEstado");
            entity.Property(e => e.IndTipoPedido).HasMaxLength(1).IsUnicode(false).HasColumnName("indTipoPedido");
            entity.Property(e => e.MargenMayor).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MargenMenor).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Mercado).HasMaxLength(1).IsUnicode(false);
            entity.Property(e => e.NombreCanal).HasMaxLength(100).IsUnicode(false).HasColumnName("nombreCanal");
            entity.Property(e => e.TipAlmacen).HasColumnName("tipAlmacen");
            entity.Property(e => e.TipoCalculo).HasMaxLength(1).IsUnicode(false);
            entity.Property(e => e.UsuarioModificacion).HasMaxLength(20).IsUnicode(false);
            entity.Property(e => e.UsuarioRegistro).HasMaxLength(20).IsUnicode(false);


            entity.HasOne(d => d.IdListaPrecioNav).WithMany(p => p.VenCanalVenta)
                .HasForeignKey(d => new { d.IdEmpresa, d.IdListaPrecio })
                .HasConstraintName("FK_ven_CanalVenta_ListaPrecio");

            entity.HasOne(l => l.PersonaCanalVenta).WithMany(d => d.CanalesVenta)
                .HasForeignKey(p => p.IdCanalVenta)
                .HasConstraintName("FK_Persona_CanalVenta");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VenCanalVentum> entity);
    }
}
