// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity.Tacama.master;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class VendedoreConfiguration : IEntityTypeConfiguration<Vendedore>
    {
        public void Configure(EntityTypeBuilder<Vendedore> entity)
        {
            entity.HasKey(e => new { e.IdPersona, e.IdEmpresa })
                .HasName("PK_Vendedores_1");

            entity.Property(e => e.IdPersona).HasColumnName("idPersona");

            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");

            entity.Property(e => e.Cargo)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.CodVendedor)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("codVendedor");

            entity.Property(e => e.FecBaja)
                .HasColumnType("smalldatetime")
                .HasColumnName("fecBaja");

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.IdDivision).HasColumnName("idDivision");

            entity.Property(e => e.IdEstablecimiento).HasColumnName("idEstablecimiento");

            entity.Property(e => e.IdVendedor).HasColumnName("idVendedor");

            entity.Property(e => e.IdZona).HasColumnName("idZona");

            entity.Property(e => e.IndEstado).HasColumnName("indEstado");

            entity.Property(e => e.IndSupervisor).HasColumnName("indSupervisor");

            entity.Property(e => e.NombreCotizacion).HasMaxLength(200);

            entity.Property(e => e.TipoVendedor)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Vendedore> entity);
    }
}
