// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity.Tacama.master;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class VenDivisionConfiguration : IEntityTypeConfiguration<VenDivision>
    {
        public void Configure(EntityTypeBuilder<VenDivision> entity)
        {
            entity.HasKey(e => new { e.IdEmpresa, e.IdDivision });

            entity.ToTable("ven_Division");

            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");

            entity.Property(e => e.IdDivision).HasColumnName("idDivision");

            entity.Property(e => e.DesDivision)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("desDivision");

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VenDivision> entity);
    }
}
