// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using IDCL.Tacama.Core.Entity.Tacama.master;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace IDCL.Tacama.Core.Contexto.Configurations
{
    public partial class ZonaTrabajoConfiguration : IEntityTypeConfiguration<ZonaTrabajo>
    {
        public void Configure(EntityTypeBuilder<ZonaTrabajo> entity)
        {
            entity.HasKey(e => new { e.IdEmpresa, e.IdLocal, e.IdEstablecimiento, e.IdZona });

            entity.ToTable("ZonaTrabajo");

            entity.Property(e => e.IdEmpresa).HasColumnName("idEmpresa");

            entity.Property(e => e.IdLocal).HasColumnName("idLocal");

            entity.Property(e => e.IdEstablecimiento).HasColumnName("idEstablecimiento");

            entity.Property(e => e.IdZona).HasColumnName("idZona");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.FechaModificacion).HasColumnType("smalldatetime");

            entity.Property(e => e.FechaRegistro).HasColumnType("smalldatetime");

            entity.Property(e => e.IdCcostos)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("idCCostos");

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioRegistro)
                .HasMaxLength(20)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ZonaTrabajo> entity);
    }
}
